### **Welcome to the Python Basics Course! 🦁**

As a start we take the opportunity to emphasize on the importance of understanding **documentation** when using different libraries.
Example of useful documentation for Pandas 🐼  Library: https://pandas.pydata.org/docs/index.html

In [128]:
import pandas as pd
import numpy as np
import seaborn as sns

# Load the data

tips_df = sns.load_dataset("tips")
#add a column with date
tips_df['date']=pd.date_range(start='2025-01-01', periods=len(tips_df), freq='D')

In [32]:
tips_df.head()

   total_bill   tip     sex smoker  day    time  size       date
0       16.99  1.01  Female     No  Sun  Dinner     2 2025-01-01
1       10.34  1.66    Male     No  Sun  Dinner     3 2025-01-02
2       21.01  3.50    Male     No  Sun  Dinner     3 2025-01-03
3       23.68  3.31    Male     No  Sun  Dinner     2 2025-01-04
4       24.59  3.61  Female     No  Sun  Dinner     4 2025-01-05

In [33]:
#check data types
tips_df.dtypes

total_bill           float64
tip                  float64
sex                 category
smoker              category
day                 category
time                category
size                   int64
date          datetime64[ns]
dtype: object

# **↩ Changing Column Names**

In [78]:
#checking all column names
tips_df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size', 'date',
       'year_month', 'year'],
      dtype='object')

In [81]:
#change column name size to be more intuitive
tips_df.rename(columns={'size':'party_size'},inplace=True)

In [83]:
tips_df

,total_bill,tip,sex,smoker,day,time,party_size,date,year_month,year
0,16.99,1.01,Female,No,Sun,Dinner,2,2025-01-01,2025-01,2025
1,10.34,1.66,Male,No,Sun,Dinner,3,2025-01-02,2025-01,2025
2,21.01,3.50,Male,No,Sun,Dinner,3,2025-01-03,2025-01,2025
3,23.68,3.31,Male,No,Sun,Dinner,2,2025-01-04,2025-01,2025
4,24.59,3.61,Female,No,Sun,Dinner,4,2025-01-05,2025-01,2025
...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,2025-08-28,2025-08,2025
240,27.18,2.00,Female,Yes,Sat,Dinner,2,2025-08-29,2025-08,2025
241,22.67,2.00,Male,Yes,Sat,Dinner,2,2025-08-30,2025-08,2025
242,17.82,1.75,Male,No,Sat,Dinner,2,2025-08-31,2025-08,2025
243,18.78,3.00,Female,No,Thur,Dinner,2,2025-09-01,2025-09,2025

# **↩ Changing data types**

In [62]:
#check distinct values in size
tips_df['size'].unique()

['2', '3', '4', '1', '6', '5']
Categories (6, object): ['1', '2', '3', '4', '5', '6']

In [63]:
#changing size to str
tips_df['size']=tips_df['size'].astype('category')
tips_df.dtypes

total_bill           float64
tip                  float64
sex                 category
smoker              category
day                 category
time                category
size                category
date          datetime64[ns]
year_month         period[M]
year                   int32
dtype: object

In [65]:
tips_df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
date          0
year_month    0
year          0
dtype: int64

# **⏲** **Changing daily data to monthly/yearly**

In [34]:
# what are the monthly sales ?
#create a new column with year-month
tips_df['year_month']=tips_df['date'].dt.to_period('M')
tips_df.sort_values(by='date',inplace=True)
tips_df

     total_bill   tip     sex smoker   day    time  size       date year_month
0         16.99  1.01  Female     No   Sun  Dinner     2 2025-01-01    2025-01
1         10.34  1.66    Male     No   Sun  Dinner     3 2025-01-02    2025-01
2         21.01  3.50    Male     No   Sun  Dinner     3 2025-01-03    2025-01
3         23.68  3.31    Male     No   Sun  Dinner     2 2025-01-04    2025-01
4         24.59  3.61  Female     No   Sun  Dinner     4 2025-01-05    2025-01
..          ...   ...     ...    ...   ...     ...   ...        ...        ...
239       29.03  5.92    Male     No   Sat  Dinner     3 2025-08-28    2025-08
240       27.18  2.00  Female    Yes   Sat  Dinner     2 2025-08-29    2025-08
241       22.67  2.00    Male    Yes   Sat  Dinner     2 2025-08-30    2025-08
242       17.82  1.75    Male     No   Sat  Dinner     2 2025-08-31    2025-08
243       18.78  3.00  Female     No  Thur  Dinner     2 2025-09-01    2025-09

[244 rows x 9 columns]

In [55]:
#monthly sales
monthly_sales=tips_df.groupby('year_month')['total_bill'].sum()
monthly_sales

year_month
2025-01    575.39
2025-02    574.46
2025-03    602.59
2025-04    620.59
2025-05    504.69
2025-06    654.20
2025-07    685.37
2025-08    591.70
2025-09     18.78
Freq: M, Name: total_bill, dtype: float64

In [57]:
monthly_sales.sum()

np.float64(4827.7699999999995)

In [42]:
tips_df['year']=tips_df['date'].dt.year
yearly_sales=tips_df.groupby('year')['total_bill'].sum()
yearly_sales

year
2025    4827.77
Name: total_bill, dtype: float64

# **⚠ Null Values**

In [116]:
#setting tip to nulll when tip is >9
tips_df.loc[tips_df['tip']>9,'tip']=None

In [71]:
#fidning null counrts in each column
tips_df.isnull().sum()

total_bill    0
tip           1
sex           0
smoker        0
day           0
time          0
size          0
date          0
year_month    0
year          0
dtype: int64

In [74]:
#replacing null value with 10
tips_df['tip']=tips_df['tip'].fillna(10)

In [75]:
#check to see null value replaced
tips_df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
date          0
year_month    0
year          0
dtype: int64

# ➕ ➖ **Basic Aritmethic Operations**

What is the % of tip offered from the total bill ?

In [129]:
tips_df['%tip_from_total_bill']=(tips_df['tip']/tips_df['total_bill'])*100
tips_df['%tip_from_total_bill']=tips_df['%tip_from_total_bill'].round(1)
tips_df.head()

,total_bill,tip,sex,smoker,day,time,size,date,%tip_from_total_bill
0,16.99,1.01,Female,No,Sun,Dinner,2,2025-01-01,5.9
1,10.34,1.66,Male,No,Sun,Dinner,3,2025-01-02,16.1
2,21.01,3.50,Male,No,Sun,Dinner,3,2025-01-03,16.7
3,23.68,3.31,Male,No,Sun,Dinner,2,2025-01-04,14.0
4,24.59,3.61,Female,No,Sun,Dinner,4,2025-01-05,14.7

# **🏷 Labelling Data**
Let's say you would like to flag sales occuring on Public Holidays

In [111]:
#let's say we have the days of holidays in a list

public_holidays=['2025-01-01','2025-02-10','2025-03-19','2025-03-31']

In [113]:
#creating a column that labels sales on public holidays
tips_df['public_holiday']=tips_df['date'].isin(public_holidays)

/tmp/ipykernel_11611/571826390.py:2: FutureWarning: The behavior of 'isin' with dtype=datetime64[ns] and castable values (e.g. strings) is deprecated. In a future version, these will not be considered matching by isin. Explicitly cast to the appropriate dtype before calling isin instead.
  tips_df['public_holiday']=tips_df['date'].isin(public_holidays)

In [127]:
tips_df.head()

,total_bill,tip,sex,smoker,day,time,party_size,date,year_month,year,public_holiday,%tip_from_total_bill
0,16.99,1.01,Female,No,Sun,Dinner,2,2025-01-01,2025-01,2025,True,5.9
1,10.34,1.66,Male,No,Sun,Dinner,3,2025-01-02,2025-01,2025,False,16.1
2,21.01,3.50,Male,No,Sun,Dinner,3,2025-01-03,2025-01,2025,False,16.7
3,23.68,3.31,Male,No,Sun,Dinner,2,2025-01-04,2025-01,2025,False,14.0
4,24.59,3.61,Female,No,Sun,Dinner,4,2025-01-05,2025-01,2025,False,14.7

Labelling based on Conditions

In [131]:
tips_df.shape

(244, 9)

In [141]:

# Define the logical conditions for selection
# You can combine multiple criteria using bitwise operators: & (AND), | (OR)
conditions = [
    (tips_df['%tip_from_total_bill'] <10) ,
    (tips_df['%tip_from_total_bill'] >=10)
]

# Define the corresponding values to assign for each condition
choices = [ 'Silver', 'Gold']

# Create the new column using np.select
# The 'default' argument specifies the value to use if no conditions are met
tips_df['customer_tier'] = np.select(conditions, choices,'Unclassified')

tips_df.head(5)

,total_bill,tip,sex,smoker,day,time,size,date,%tip_from_total_bill,customer_tier
0,16.99,1.01,Female,No,Sun,Dinner,2,2025-01-01,5.9,Silver
1,10.34,1.66,Male,No,Sun,Dinner,3,2025-01-02,16.1,Gold
2,21.01,3.50,Male,No,Sun,Dinner,3,2025-01-03,16.7,Gold
3,23.68,3.31,Male,No,Sun,Dinner,2,2025-01-04,14.0,Gold
4,24.59,3.61,Female,No,Sun,Dinner,4,2025-01-05,14.7,Gold

# ⚖ Group By

In [85]:
#find the sum of  sales generated by time of service
tips_df.groupby('time')['total_bill'].sum()

/tmp/ipykernel_11611/2702684033.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips_df.groupby('time')['total_bill'].sum()

time
Lunch     1167.47
Dinner    3660.30
Name: total_bill, dtype: float64

In [87]:
# Applying group by with agg
#find the sum of sales and mean tip generated by time of service
tips_df.groupby('time').agg({'total_bill':'sum','tip':'mean' }).rename(columns={'total_bill':'total_bill_sum','tip':'tip_mean'})
#

/tmp/ipykernel_11611/789761943.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips_df.groupby('time').agg({'total_bill':'sum','tip':'mean' }).rename(columns={'total_bill':'total_bill_sum','tip':'tip_mean'})

        total_bill_sum  tip_mean
time
Lunch          1167.47  2.728088
Dinner         3660.30  3.102670

In [88]:
tips_df

,total_bill,tip,sex,smoker,day,time,party_size,date,year_month,year
0,16.99,1.01,Female,No,Sun,Dinner,2,2025-01-01,2025-01,2025
1,10.34,1.66,Male,No,Sun,Dinner,3,2025-01-02,2025-01,2025
2,21.01,3.50,Male,No,Sun,Dinner,3,2025-01-03,2025-01,2025
3,23.68,3.31,Male,No,Sun,Dinner,2,2025-01-04,2025-01,2025
4,24.59,3.61,Female,No,Sun,Dinner,4,2025-01-05,2025-01,2025
...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,2025-08-28,2025-08,2025
240,27.18,2.00,Female,Yes,Sat,Dinner,2,2025-08-29,2025-08,2025
241,22.67,2.00,Male,Yes,Sat,Dinner,2,2025-08-30,2025-08,2025
242,17.82,1.75,Male,No,Sat,Dinner,2,2025-08-31,2025-08,2025
243,18.78,3.00,Female,No,Thur,Dinner,2,2025-09-01,2025-09,2025

# 🔝 Most Popular Category

🚬 **Management are currently considering extending the restaurant area and are unsure whether to make it a smoking zone**:🚬

They are also unsure of what table sizes they should purchased 🤔

In [89]:
#Are our customers mostly smokers or non smokers?
tips_df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [90]:
#What are the most common party sizes?
tips_df['party_size'].value_counts()

party_size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

# **➿ For Loops**

In [91]:
tips_df.head()

,total_bill,tip,sex,smoker,day,time,party_size,date,year_month,year
0,16.99,1.01,Female,No,Sun,Dinner,2,2025-01-01,2025-01,2025
1,10.34,1.66,Male,No,Sun,Dinner,3,2025-01-02,2025-01,2025
2,21.01,3.50,Male,No,Sun,Dinner,3,2025-01-03,2025-01,2025
3,23.68,3.31,Male,No,Sun,Dinner,2,2025-01-04,2025-01,2025
4,24.59,3.61,Female,No,Sun,Dinner,4,2025-01-05,2025-01,2025

In [94]:
tips_df.groupby('day')

/tmp/ipykernel_11611/2017156701.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips_df.groupby('day')

In [104]:
#for each day of the week we find the mean sales and mean tip
for day, group in tips_df.groupby('day'):
  avg_tip=group['tip'].mean()
  avg_sales=group['total_bill'].mean()
  print(f"{day}:avg_tip,avg_sales:{avg_tip},{avg_sales}")

Thur:avg_tip,avg_sales:2.771451612903225,17.682741935483868
Fri:avg_tip,avg_sales:2.7347368421052627,17.15157894736842
Sat:avg_tip,avg_sales:2.993103448275862,20.441379310344825
Sun:avg_tip,avg_sales:3.2551315789473687,21.41

/tmp/ipykernel_11611/517025852.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for day, group in tips_df.groupby('day'):

In [105]:
#this can also be achieved with a group by
tips_df.groupby('day').agg({'tip':'mean','total_bill':'mean'})

/tmp/ipykernel_11611/341138084.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips_df.groupby('day').agg({'tip':'mean','total_bill':'mean'})

           tip  total_bill
day
Thur  2.771452   17.682742
Fri   2.734737   17.151579
Sat   2.993103   20.441379
Sun   3.255132   21.410000

# **🪡 Joins**